[package]
name = "osu-mapsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
data-encoding = "2.3.3"
sha2 = "0.10.6"
thiserror = "1.0.38"
